name: certbot-dns-inwx
base: core24
summary: INWX DNS Authenticator plugin for Certbot
description: INWX DNS Authenticator plugin for Certbot
license: Apache-2.0
grade: stable
confinement: strict
adopt-info: certbot-dns-inwx
platforms:
  amd64:
  arm64:
  armhf:

parts:
  certbot-dns-inwx:
    plugin: python
    source: .
    override-pull: |
        craftctl default
        craftctl set version=$(grep ^version "${CRAFT_PART_SRC}/setup.py" | cut -f2 -d= | tr -d "'[:space:]")
    build-environment:
      - SNAP_BUILD: "True"
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        craftctl default
        mkdir -p $CRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP\certbot-shared
